# --------------------------------------------------------------------------------------------
# Copyright (c) Microsoft Corporation. All rights reserved.
# Licensed under the MIT License. See License.txt in the project root for license information.
#
# Code generated by aaz-dev-tools
# --------------------------------------------------------------------------------------------

# pylint: skip-file
# flake8: noqa

from azure.cli.core.aaz import *


@register_command(
    "container-registry registry update",
)
class Update(AAZCommand):
    """Update a container registry with the specified parameters.
    """

    _aaz_info = {
        "version": "2024-11-01-preview",
        "resources": [
            ["mgmt-plane", "/subscriptions/{}/resourcegroups/{}/providers/microsoft.containerregistry/registries/{}", "2024-11-01-preview"],
        ]
    }

    AZ_SUPPORT_NO_WAIT = True

    def _handler(self, command_args):
        super()._handler(command_args)
        return self.build_lro_poller(self._execute_operations, self._output)

    _args_schema = None

    @classmethod
    def _build_arguments_schema(cls, *args, **kwargs):
        if cls._args_schema is not None:
            return cls._args_schema
        cls._args_schema = super()._build_arguments_schema(*args, **kwargs)

        # define Arg Group ""

        _args_schema = cls._args_schema
        _args_schema.registry_name = AAZStrArg(
            options=["-n", "--name", "--registry-name"],
            help="The name of the container registry.",
            required=True,
            id_part="name",
            fmt=AAZStrArgFormat(
                pattern="^[a-zA-Z0-9]*$",
                max_length=50,
                min_length=5,
            ),
        )
        _args_schema.resource_group = AAZResourceGroupNameArg(
            required=True,
        )

        # define Arg Group "Identity"

        _args_schema = cls._args_schema
        _args_schema.mi_system_assigned = AAZStrArg(
            options=["--system-assigned", "--mi-system-assigned"],
            arg_group="Identity",
            help="Set the system managed identity.",
            blank="True",
        )
        _args_schema.mi_user_assigned = AAZListArg(
            options=["--user-assigned", "--mi-user-assigned"],
            arg_group="Identity",
            help="Set the user managed identities.",
            blank=[],
        )

        mi_user_assigned = cls._args_schema.mi_user_assigned
        mi_user_assigned.Element = AAZStrArg()

        # define Arg Group "Properties"

        _args_schema = cls._args_schema
        _args_schema.admin_user_enabled = AAZBoolArg(
            options=["--admin-user-enabled"],
            arg_group="Properties",
            help="The value that indicates whether the admin user is enabled.",
        )
        _args_schema.anonymous_pull_enabled = AAZBoolArg(
            options=["--anonymous-pull-enabled"],
            arg_group="Properties",
            help="Enables registry-wide pull from unauthenticated clients.",
        )
        _args_schema.data_endpoint_enabled = AAZBoolArg(
            options=["--data-endpoint-enabled"],
            arg_group="Properties",
            help="Enable a single data endpoint per region for serving data.",
        )
        _args_schema.encryption = AAZObjectArg(
            options=["--encryption"],
            arg_group="Properties",
            help="The encryption settings of container registry.",
        )
        _args_schema.metadata_search = AAZStrArg(
            options=["--metadata-search"],
            arg_group="Properties",
            help="Determines whether registry artifacts are indexed for metadata search.",
            default="Disabled",
            enum={"Disabled": "Disabled", "Enabled": "Enabled"},
        )
        _args_schema.network_rule_bypass_options = AAZStrArg(
            options=["--network-rule-bypass-options"],
            arg_group="Properties",
            help="Whether to allow trusted Azure services to access a network restricted registry.",
            default="AzureServices",
            enum={"AzureServices": "AzureServices", "None": "None"},
        )
        _args_schema.network_rule_set = AAZObjectArg(
            options=["--network-rule-set"],
            arg_group="Properties",
            help="The network rule set for a container registry.",
        )
        _args_schema.policies = AAZObjectArg(
            options=["--policies"],
            arg_group="Properties",
            help="The policies for a container registry.",
        )
        _args_schema.public_network_access = AAZStrArg(
            options=["--public-network-access"],
            arg_group="Properties",
            help="Whether or not public network access is allowed for the container registry.",
            enum={"Disabled": "Disabled", "Enabled": "Enabled"},
        )

        encryption = cls._args_schema.encryption
        encryption.key_vault_properties = AAZObjectArg(
            options=["key-vault-properties"],
            help="Key vault properties.",
        )
        encryption.status = AAZStrArg(
            options=["status"],
            help="Indicates whether or not the encryption is enabled for container registry.",
            enum={"disabled": "disabled", "enabled": "enabled"},
        )

        key_vault_properties = cls._args_schema.encryption.key_vault_properties
        key_vault_properties.identity = AAZStrArg(
            options=["identity"],
            help="The client id of the identity which will be used to access key vault.",
        )
        key_vault_properties.key_identifier = AAZStrArg(
            options=["key-identifier"],
            help="Key vault uri to access the encryption key.",
        )

        network_rule_set = cls._args_schema.network_rule_set
        network_rule_set.default_action = AAZStrArg(
            options=["default-action"],
            help="The default action of allow or deny when no other rules match.",
            required=True,
            default="Allow",
            enum={"Allow": "Allow", "Deny": "Deny"},
        )
        network_rule_set.ip_rules = AAZListArg(
            options=["ip-rules"],
            help="The IP ACL rules.",
        )

        ip_rules = cls._args_schema.network_rule_set.ip_rules
        ip_rules.Element = AAZObjectArg()

        _element = cls._args_schema.network_rule_set.ip_rules.Element
        _element.action = AAZStrArg(
            options=["action"],
            help="The action of IP ACL rule.",
            default="Allow",
            enum={"Allow": "Allow"},
        )
        _element.value = AAZStrArg(
            options=["value"],
            help="Specifies the IP or IP range in CIDR format. Only IPV4 address is allowed.",
            required=True,
        )

        policies = cls._args_schema.policies
        policies.azure_ad_authentication_as_arm_policy = AAZObjectArg(
            options=["azure-ad-authentication-as-arm-policy"],
            help="The policy for using ARM audience token for a container registry.",
        )
        policies.export_policy = AAZObjectArg(
            options=["export-policy"],
            help="The export policy for a container registry.",
        )
        policies.quarantine_policy = AAZObjectArg(
            options=["quarantine-policy"],
            help="The quarantine policy for a container registry.",
        )
        policies.retention_policy = AAZObjectArg(
            options=["retention-policy"],
            help="The retention policy for a container registry.",
        )
        policies.soft_delete_policy = AAZObjectArg(
            options=["soft-delete-policy"],
            help="The soft delete policy for a container registry.",
        )
        policies.trust_policy = AAZObjectArg(
            options=["trust-policy"],
            help="The content trust policy for a container registry.",
        )

        azure_ad_authentication_as_arm_policy = cls._args_schema.policies.azure_ad_authentication_as_arm_policy
        azure_ad_authentication_as_arm_policy.status = AAZStrArg(
            options=["status"],
            help="The value that indicates whether the policy is enabled or not.",
            default="enabled",
            enum={"disabled": "disabled", "enabled": "enabled"},
        )

        export_policy = cls._args_schema.policies.export_policy
        export_policy.status = AAZStrArg(
            options=["status"],
            help="The value that indicates whether the policy is enabled or not.",
            default="enabled",
            enum={"disabled": "disabled", "enabled": "enabled"},
        )

        quarantine_policy = cls._args_schema.policies.quarantine_policy
        quarantine_policy.status = AAZStrArg(
            options=["status"],
            help="The value that indicates whether the policy is enabled or not.",
            default="disabled",
            enum={"disabled": "disabled", "enabled": "enabled"},
        )

        retention_policy = cls._args_schema.policies.retention_policy
        retention_policy.days = AAZIntArg(
            options=["days"],
            help="The number of days to retain an untagged manifest after which it gets purged.",
            default=7,
        )
        retention_policy.status = AAZStrArg(
            options=["status"],
            help="The value that indicates whether the policy is enabled or not.",
            default="disabled",
            enum={"disabled": "disabled", "enabled": "enabled"},
        )

        soft_delete_policy = cls._args_schema.policies.soft_delete_policy
        soft_delete_policy.retention_days = AAZIntArg(
            options=["retention-days"],
            help="The number of days after which a soft-deleted item is permanently deleted.",
            default=7,
        )
        soft_delete_policy.status = AAZStrArg(
            options=["status"],
            help="The value that indicates whether the policy is enabled or not.",
            default="disabled",
            enum={"disabled": "disabled", "enabled": "enabled"},
        )

        trust_policy = cls._args_schema.policies.trust_policy
        trust_policy.status = AAZStrArg(
            options=["status"],
            help="The value that indicates whether the policy is enabled or not.",
            default="disabled",
            enum={"disabled": "disabled", "enabled": "enabled"},
        )
        trust_policy.type = AAZStrArg(
            options=["type"],
            help="The type of trust policy.",
            default="Notary",
            enum={"Notary": "Notary"},
        )

        # define Arg Group "RegistryUpdateParameters"

        _args_schema = cls._args_schema
        _args_schema.sku = AAZObjectArg(
            options=["--sku"],
            arg_group="RegistryUpdateParameters",
            help="The SKU of the container registry.",
        )
        _args_schema.tags = AAZDictArg(
            options=["--tags"],
            arg_group="RegistryUpdateParameters",
            help="The tags for the container registry.",
        )

        sku = cls._args_schema.sku
        sku.name = AAZStrArg(
            options=["name"],
            help="The SKU name of the container registry. Required for registry creation.",
            required=True,
            enum={"Basic": "Basic", "Classic": "Classic", "Premium": "Premium", "Standard": "Standard"},
        )

        tags = cls._args_schema.tags
        tags.Element = AAZStrArg()
        return cls._args_schema

    def _execute_operations(self):
        self.pre_operations()
        yield self.RegistriesUpdate(ctx=self.ctx)()
        self.post_operations()

    @register_callback
    def pre_operations(self):
        pass

    @register_callback
    def post_operations(self):
        pass

    def _output(self, *args, **kwargs):
        result = self.deserialize_output(self.ctx.vars.instance, client_flatten=True)
        return result

    class RegistriesUpdate(AAZHttpOperation):
        CLIENT_TYPE = "MgmtClient"

        def __call__(self, *args, **kwargs):
            request = self.make_request()
            session = self.client.send_request(request=request, stream=False, **kwargs)
            if session.http_response.status_code in [202]:
                return self.client.build_lro_polling(
                    self.ctx.args.no_wait,
                    session,
                    self.on_200_201,
                    self.on_error,
                    lro_options={"final-state-via": "azure-async-operation"},
                    path_format_arguments=self.url_parameters,
                )
            if session.http_response.status_code in [200, 201]:
                return self.client.build_lro_polling(
                    self.ctx.args.no_wait,
                    session,
                    self.on_200_201,
                    self.on_error,
                    lro_options={"final-state-via": "azure-async-operation"},
                    path_format_arguments=self.url_parameters,
                )

            return self.on_error(session.http_response)

        @property
        def url(self):
            return self.client.format_url(
                "/subscriptions/{subscriptionId}/resourceGroups/{resourceGroupName}/providers/Microsoft.ContainerRegistry/registries/{registryName}",
                **self.url_parameters
            )

        @property
        def method(self):
            return "PATCH"

        @property
        def error_format(self):
            return "MgmtErrorFormat"

        @property
        def url_parameters(self):
            parameters = {
                **self.serialize_url_param(
                    "registryName", self.ctx.args.registry_name,
                    required=True,
                ),
                **self.serialize_url_param(
                    "resourceGroupName", self.ctx.args.resource_group,
                    required=True,
                ),
                **self.serialize_url_param(
                    "subscriptionId", self.ctx.subscription_id,
                    required=True,
                ),
            }
            return parameters

        @property
        def query_parameters(self):
            parameters = {
                **self.serialize_query_param(
                    "api-version", "2024-11-01-preview",
                    required=True,
                ),
            }
            return parameters

        @property
        def header_parameters(self):
            parameters = {
                **self.serialize_header_param(
                    "Content-Type", "application/json",
                ),
                **self.serialize_header_param(
                    "Accept", "application/json",
                ),
            }
            return parameters

        @property
        def content(self):
            _content_value, _builder = self.new_content_builder(
                self.ctx.args,
                typ=AAZObjectType,
                typ_kwargs={"flags": {"required": True, "client_flatten": True}}
            )
            _builder.set_prop("identity", AAZIdentityObjectType)
            _builder.set_prop("properties", AAZObjectType, typ_kwargs={"flags": {"client_flatten": True}})
            _builder.set_prop("sku", AAZObjectType, ".sku")
            _builder.set_prop("tags", AAZDictType, ".tags")

            identity = _builder.get(".identity")
            if identity is not None:
                identity.set_prop("userAssigned", AAZListType, ".mi_user_assigned", typ_kwargs={"flags": {"action": "create"}})
                identity.set_prop("systemAssigned", AAZStrType, ".mi_system_assigned", typ_kwargs={"flags": {"action": "create"}})

            user_assigned = _builder.get(".identity.userAssigned")
            if user_assigned is not None:
                user_assigned.set_elements(AAZStrType, ".")

            properties = _builder.get(".properties")
            if properties is not None:
                properties.set_prop("adminUserEnabled", AAZBoolType, ".admin_user_enabled")
                properties.set_prop("anonymousPullEnabled", AAZBoolType, ".anonymous_pull_enabled")
                properties.set_prop("dataEndpointEnabled", AAZBoolType, ".data_endpoint_enabled")
                properties.set_prop("encryption", AAZObjectType, ".encryption")
                properties.set_prop("metadataSearch", AAZStrType, ".metadata_search")
                properties.set_prop("networkRuleBypassOptions", AAZStrType, ".network_rule_bypass_options")
                properties.set_prop("networkRuleSet", AAZObjectType, ".network_rule_set")
                properties.set_prop("policies", AAZObjectType, ".policies")
                properties.set_prop("publicNetworkAccess", AAZStrType, ".public_network_access")

            encryption = _builder.get(".properties.encryption")
            if encryption is not None:
                encryption.set_prop("keyVaultProperties", AAZObjectType, ".key_vault_properties")
                encryption.set_prop("status", AAZStrType, ".status")

            key_vault_properties = _builder.get(".properties.encryption.keyVaultProperties")
            if key_vault_properties is not None:
                key_vault_properties.set_prop("identity", AAZStrType, ".identity")
                key_vault_properties.set_prop("keyIdentifier", AAZStrType, ".key_identifier")

            network_rule_set = _builder.get(".properties.networkRuleSet")
            if network_rule_set is not None:
                network_rule_set.set_prop("defaultAction", AAZStrType, ".default_action", typ_kwargs={"flags": {"required": True}})
                network_rule_set.set_prop("ipRules", AAZListType, ".ip_rules")

            ip_rules = _builder.get(".properties.networkRuleSet.ipRules")
            if ip_rules is not None:
                ip_rules.set_elements(AAZObjectType, ".")

            _elements = _builder.get(".properties.networkRuleSet.ipRules[]")
            if _elements is not None:
                _elements.set_prop("action", AAZStrType, ".action")
                _elements.set_prop("value", AAZStrType, ".value", typ_kwargs={"flags": {"required": True}})

            policies = _builder.get(".properties.policies")
            if policies is not None:
                policies.set_prop("azureADAuthenticationAsArmPolicy", AAZObjectType, ".azure_ad_authentication_as_arm_policy")
                policies.set_prop("exportPolicy", AAZObjectType, ".export_policy")
                policies.set_prop("quarantinePolicy", AAZObjectType, ".quarantine_policy")
                policies.set_prop("retentionPolicy", AAZObjectType, ".retention_policy")
                policies.set_prop("softDeletePolicy", AAZObjectType, ".soft_delete_policy")
                policies.set_prop("trustPolicy", AAZObjectType, ".trust_policy")

            azure_ad_authentication_as_arm_policy = _builder.get(".properties.policies.azureADAuthenticationAsArmPolicy")
            if azure_ad_authentication_as_arm_policy is not None:
                azure_ad_authentication_as_arm_policy.set_prop("status", AAZStrType, ".status")

            export_policy = _builder.get(".properties.policies.exportPolicy")
            if export_policy is not None:
                export_policy.set_prop("status", AAZStrType, ".status")

            quarantine_policy = _builder.get(".properties.policies.quarantinePolicy")
            if quarantine_policy is not None:
                quarantine_policy.set_prop("status", AAZStrType, ".status")

            retention_policy = _builder.get(".properties.policies.retentionPolicy")
            if retention_policy is not None:
                retention_policy.set_prop("days", AAZIntType, ".days")
                retention_policy.set_prop("status", AAZStrType, ".status")

            soft_delete_policy = _builder.get(".properties.policies.softDeletePolicy")
            if soft_delete_policy is not None:
                soft_delete_policy.set_prop("retentionDays", AAZIntType, ".retention_days")
                soft_delete_policy.set_prop("status", AAZStrType, ".status")

            trust_policy = _builder.get(".properties.policies.trustPolicy")
            if trust_policy is not None:
                trust_policy.set_prop("status", AAZStrType, ".status")
                trust_policy.set_prop("type", AAZStrType, ".type")

            sku = _builder.get(".sku")
            if sku is not None:
                sku.set_prop("name", AAZStrType, ".name", typ_kwargs={"flags": {"required": True}})

            tags = _builder.get(".tags")
            if tags is not None:
                tags.set_elements(AAZStrType, ".")

            return self.serialize_content(_content_value)

        def on_200_201(self, session):
            data = self.deserialize_http_content(session)
            self.ctx.set_var(
                "instance",
                data,
                schema_builder=self._build_schema_on_200_201
            )

        _schema_on_200_201 = None

        @classmethod
        def _build_schema_on_200_201(cls):
            if cls._schema_on_200_201 is not None:
                return cls._schema_on_200_201

            cls._schema_on_200_201 = AAZObjectType()

            _schema_on_200_201 = cls._schema_on_200_201
            _schema_on_200_201.id = AAZStrType(
                flags={"read_only": True},
            )
            _schema_on_200_201.identity = AAZIdentityObjectType()
            _schema_on_200_201.location = AAZStrType(
                flags={"required": True},
            )
            _schema_on_200_201.name = AAZStrType(
                flags={"read_only": True},
            )
            _schema_on_200_201.properties = AAZObjectType(
                flags={"client_flatten": True},
            )
            _schema_on_200_201.sku = AAZObjectType(
                flags={"required": True},
            )
            _schema_on_200_201.system_data = AAZObjectType(
                serialized_name="systemData",
                flags={"read_only": True},
            )
            _UpdateHelper._build_schema_system_data_read(_schema_on_200_201.system_data)
            _schema_on_200_201.tags = AAZDictType()
            _schema_on_200_201.type = AAZStrType(
                flags={"read_only": True},
            )

            identity = cls._schema_on_200_201.identity
            identity.principal_id = AAZStrType(
                serialized_name="principalId",
                flags={"read_only": True},
            )
            identity.tenant_id = AAZStrType(
                serialized_name="tenantId",
                flags={"read_only": True},
            )
            identity.type = AAZStrType()
            identity.user_assigned_identities = AAZDictType(
                serialized_name="userAssignedIdentities",
            )

            user_assigned_identities = cls._schema_on_200_201.identity.user_assigned_identities
            user_assigned_identities.Element = AAZObjectType()

            _element = cls._schema_on_200_201.identity.user_assigned_identities.Element
            _element.client_id = AAZStrType(
                serialized_name="clientId",
                flags={"read_only": True},
            )
            _element.principal_id = AAZStrType(
                serialized_name="principalId",
                flags={"read_only": True},
            )

            properties = cls._schema_on_200_201.properties
            properties.admin_user_enabled = AAZBoolType(
                serialized_name="adminUserEnabled",
            )
            properties.anonymous_pull_enabled = AAZBoolType(
                serialized_name="anonymousPullEnabled",
            )
            properties.auto_generated_domain_name_label_scope = AAZStrType(
                serialized_name="autoGeneratedDomainNameLabelScope",
            )
            properties.creation_date = AAZStrType(
                serialized_name="creationDate",
                flags={"read_only": True},
            )
            properties.data_endpoint_enabled = AAZBoolType(
                serialized_name="dataEndpointEnabled",
            )
            properties.data_endpoint_host_names = AAZListType(
                serialized_name="dataEndpointHostNames",
                flags={"read_only": True},
            )
            properties.encryption = AAZObjectType()
            properties.login_server = AAZStrType(
                serialized_name="loginServer",
                flags={"read_only": True},
            )
            properties.metadata_search = AAZStrType(
                serialized_name="metadataSearch",
            )
            properties.network_rule_bypass_options = AAZStrType(
                serialized_name="networkRuleBypassOptions",
            )
            properties.network_rule_set = AAZObjectType(
                serialized_name="networkRuleSet",
            )
            properties.policies = AAZObjectType()
            properties.private_endpoint_connections = AAZListType(
                serialized_name="privateEndpointConnections",
                flags={"read_only": True},
            )
            properties.provisioning_state = AAZStrType(
                serialized_name="provisioningState",
                flags={"read_only": True},
            )
            properties.public_network_access = AAZStrType(
                serialized_name="publicNetworkAccess",
            )
            properties.status = AAZObjectType(
                flags={"read_only": True},
            )
            properties.zone_redundancy = AAZStrType(
                serialized_name="zoneRedundancy",
            )

            data_endpoint_host_names = cls._schema_on_200_201.properties.data_endpoint_host_names
            data_endpoint_host_names.Element = AAZStrType()

            encryption = cls._schema_on_200_201.properties.encryption
            encryption.key_vault_properties = AAZObjectType(
                serialized_name="keyVaultProperties",
            )
            encryption.status = AAZStrType()

            key_vault_properties = cls._schema_on_200_201.properties.encryption.key_vault_properties
            key_vault_properties.identity = AAZStrType()
            key_vault_properties.key_identifier = AAZStrType(
                serialized_name="keyIdentifier",
            )
            key_vault_properties.key_rotation_enabled = AAZBoolType(
                serialized_name="keyRotationEnabled",
                flags={"read_only": True},
            )
            key_vault_properties.last_key_rotation_timestamp = AAZStrType(
                serialized_name="lastKeyRotationTimestamp",
                flags={"read_only": True},
            )
            key_vault_properties.versioned_key_identifier = AAZStrType(
                serialized_name="versionedKeyIdentifier",
                flags={"read_only": True},
            )

            network_rule_set = cls._schema_on_200_201.properties.network_rule_set
            network_rule_set.default_action = AAZStrType(
                serialized_name="defaultAction",
                flags={"required": True},
            )
            network_rule_set.ip_rules = AAZListType(
                serialized_name="ipRules",
            )

            ip_rules = cls._schema_on_200_201.properties.network_rule_set.ip_rules
            ip_rules.Element = AAZObjectType()

            _element = cls._schema_on_200_201.properties.network_rule_set.ip_rules.Element
            _element.action = AAZStrType()
            _element.value = AAZStrType(
                flags={"required": True},
            )

            policies = cls._schema_on_200_201.properties.policies
            policies.azure_ad_authentication_as_arm_policy = AAZObjectType(
                serialized_name="azureADAuthenticationAsArmPolicy",
            )
            policies.export_policy = AAZObjectType(
                serialized_name="exportPolicy",
            )
            policies.quarantine_policy = AAZObjectType(
                serialized_name="quarantinePolicy",
            )
            policies.retention_policy = AAZObjectType(
                serialized_name="retentionPolicy",
            )
            policies.soft_delete_policy = AAZObjectType(
                serialized_name="softDeletePolicy",
            )
            policies.trust_policy = AAZObjectType(
                serialized_name="trustPolicy",
            )

            azure_ad_authentication_as_arm_policy = cls._schema_on_200_201.properties.policies.azure_ad_authentication_as_arm_policy
            azure_ad_authentication_as_arm_policy.status = AAZStrType()

            export_policy = cls._schema_on_200_201.properties.policies.export_policy
            export_policy.status = AAZStrType()

            quarantine_policy = cls._schema_on_200_201.properties.policies.quarantine_policy
            quarantine_policy.status = AAZStrType()

            retention_policy = cls._schema_on_200_201.properties.policies.retention_policy
            retention_policy.days = AAZIntType()
            retention_policy.last_updated_time = AAZStrType(
                serialized_name="lastUpdatedTime",
                flags={"read_only": True},
            )
            retention_policy.status = AAZStrType()

            soft_delete_policy = cls._schema_on_200_201.properties.policies.soft_delete_policy
            soft_delete_policy.last_updated_time = AAZStrType(
                serialized_name="lastUpdatedTime",
                flags={"read_only": True},
            )
            soft_delete_policy.retention_days = AAZIntType(
                serialized_name="retentionDays",
            )
            soft_delete_policy.status = AAZStrType()

            trust_policy = cls._schema_on_200_201.properties.policies.trust_policy
            trust_policy.status = AAZStrType()
            trust_policy.type = AAZStrType()

            private_endpoint_connections = cls._schema_on_200_201.properties.private_endpoint_connections
            private_endpoint_connections.Element = AAZObjectType()

            _element = cls._schema_on_200_201.properties.private_endpoint_connections.Element
            _element.id = AAZStrType(
                flags={"read_only": True},
            )
            _element.name = AAZStrType(
                flags={"read_only": True},
            )
            _element.properties = AAZObjectType(
                flags={"client_flatten": True},
            )
            _element.system_data = AAZObjectType(
                serialized_name="systemData",
                flags={"read_only": True},
            )
            _UpdateHelper._build_schema_system_data_read(_element.system_data)
            _element.type = AAZStrType(
                flags={"read_only": True},
            )

            properties = cls._schema_on_200_201.properties.private_endpoint_connections.Element.properties
            properties.private_endpoint = AAZObjectType(
                serialized_name="privateEndpoint",
            )
            properties.private_link_service_connection_state = AAZObjectType(
                serialized_name="privateLinkServiceConnectionState",
            )
            properties.provisioning_state = AAZStrType(
                serialized_name="provisioningState",
                flags={"read_only": True},
            )

            private_endpoint = cls._schema_on_200_201.properties.private_endpoint_connections.Element.properties.private_endpoint
            private_endpoint.id = AAZStrType()

            private_link_service_connection_state = cls._schema_on_200_201.properties.private_endpoint_connections.Element.properties.private_link_service_connection_state
            private_link_service_connection_state.actions_required = AAZStrType(
                serialized_name="actionsRequired",
            )
            private_link_service_connection_state.description = AAZStrType()
            private_link_service_connection_state.status = AAZStrType()

            status = cls._schema_on_200_201.properties.status
            status.display_status = AAZStrType(
                serialized_name="displayStatus",
                flags={"read_only": True},
            )
            status.message = AAZStrType(
                flags={"read_only": True},
            )
            status.timestamp = AAZStrType(
                flags={"read_only": True},
            )

            sku = cls._schema_on_200_201.sku
            sku.name = AAZStrType(
                flags={"required": True},
            )
            sku.tier = AAZStrType(
                flags={"read_only": True},
            )

            tags = cls._schema_on_200_201.tags
            tags.Element = AAZStrType()

            return cls._schema_on_200_201


class _UpdateHelper:
    """Helper class for Update"""

    _schema_system_data_read = None

    @classmethod
    def _build_schema_system_data_read(cls, _schema):
        if cls._schema_system_data_read is not None:
            _schema.created_at = cls._schema_system_data_read.created_at
            _schema.created_by = cls._schema_system_data_read.created_by
            _schema.created_by_type = cls._schema_system_data_read.created_by_type
            _schema.last_modified_at = cls._schema_system_data_read.last_modified_at
            _schema.last_modified_by = cls._schema_system_data_read.last_modified_by
            _schema.last_modified_by_type = cls._schema_system_data_read.last_modified_by_type
            return

        cls._schema_system_data_read = _schema_system_data_read = AAZObjectType(
            flags={"read_only": True}
        )

        system_data_read = _schema_system_data_read
        system_data_read.created_at = AAZStrType(
            serialized_name="createdAt",
        )
        system_data_read.created_by = AAZStrType(
            serialized_name="createdBy",
        )
        system_data_read.created_by_type = AAZStrType(
            serialized_name="createdByType",
        )
        system_data_read.last_modified_at = AAZStrType(
            serialized_name="lastModifiedAt",
        )
        system_data_read.last_modified_by = AAZStrType(
            serialized_name="lastModifiedBy",
        )
        system_data_read.last_modified_by_type = AAZStrType(
            serialized_name="lastModifiedByType",
        )

        _schema.created_at = cls._schema_system_data_read.created_at
        _schema.created_by = cls._schema_system_data_read.created_by
        _schema.created_by_type = cls._schema_system_data_read.created_by_type
        _schema.last_modified_at = cls._schema_system_data_read.last_modified_at
        _schema.last_modified_by = cls._schema_system_data_read.last_modified_by
        _schema.last_modified_by_type = cls._schema_system_data_read.last_modified_by_type


__all__ = ["Update"]
