# --------------------------------------------------------------------------------------------
# Copyright (c) Microsoft Corporation. All rights reserved.
# Licensed under the MIT License. See License.txt in the project root for license information.
#
# Code generated by aaz-dev-tools
# --------------------------------------------------------------------------------------------

# pylint: skip-file
# flake8: noqa

from azure.cli.core.aaz import *


@register_command(
    "container-registry registry identity remove",
)
class Remove(AAZCommand):
    """Remove the user or system managed identities.
    """

    _aaz_info = {
        "version": "2024-11-01-preview",
        "resources": [
            ["mgmt-plane", "/subscriptions/{}/resourcegroups/{}/providers/microsoft.containerregistry/registries/{}", "2024-11-01-preview", "identity"],
        ]
    }

    AZ_SUPPORT_NO_WAIT = True

    def _handler(self, command_args):
        super()._handler(command_args)
        self.SubresourceSelector(ctx=self.ctx, name="subresource")
        return self.build_lro_poller(self._execute_operations, self._output)

    _args_schema = None

    @classmethod
    def _build_arguments_schema(cls, *args, **kwargs):
        if cls._args_schema is not None:
            return cls._args_schema
        cls._args_schema = super()._build_arguments_schema(*args, **kwargs)

        # define Arg Group ""

        _args_schema = cls._args_schema
        _args_schema.registry_name = AAZStrArg(
            options=["-n", "--name", "--registry-name"],
            help="The name of the container registry.",
            required=True,
            fmt=AAZStrArgFormat(
                pattern="^[a-zA-Z0-9]*$",
                max_length=50,
                min_length=5,
            ),
        )
        _args_schema.resource_group = AAZResourceGroupNameArg(
            required=True,
        )

        # define Arg Group "RegistryUpdateParameters.identity"

        _args_schema = cls._args_schema
        _args_schema.mi_system_assigned = AAZStrArg(
            options=["--system-assigned", "--mi-system-assigned"],
            arg_group="RegistryUpdateParameters.identity",
            help="Set the system managed identity.",
            blank="True",
        )
        _args_schema.mi_user_assigned = AAZListArg(
            options=["--user-assigned", "--mi-user-assigned"],
            arg_group="RegistryUpdateParameters.identity",
            help="Set the user managed identities.",
            blank=[],
        )

        mi_user_assigned = cls._args_schema.mi_user_assigned
        mi_user_assigned.Element = AAZStrArg()
        return cls._args_schema

    def _execute_operations(self):
        self.pre_operations()
        self.RegistriesGet(ctx=self.ctx)()
        self.pre_instance_update(self.ctx.selectors.subresource.required())
        self.InstanceUpdateByJson(ctx=self.ctx)()
        self.post_instance_update(self.ctx.selectors.subresource.required())
        yield self.RegistriesUpdate(ctx=self.ctx)()
        self.post_operations()

    @register_callback
    def pre_operations(self):
        pass

    @register_callback
    def post_operations(self):
        pass

    @register_callback
    def pre_instance_update(self, instance):
        pass

    @register_callback
    def post_instance_update(self, instance):
        pass

    def _output(self, *args, **kwargs):
        result = self.deserialize_output(self.ctx.selectors.subresource.required(), client_flatten=True)
        return result

    class SubresourceSelector(AAZJsonSelector):

        def _get(self):
            result = self.ctx.vars.instance
            return result.identity

        def _set(self, value):
            result = self.ctx.vars.instance
            result.identity = value
            return

    class RegistriesGet(AAZHttpOperation):
        CLIENT_TYPE = "MgmtClient"

        def __call__(self, *args, **kwargs):
            request = self.make_request()
            session = self.client.send_request(request=request, stream=False, **kwargs)
            if session.http_response.status_code in [200]:
                return self.on_200(session)

            return self.on_error(session.http_response)

        @property
        def url(self):
            return self.client.format_url(
                "/subscriptions/{subscriptionId}/resourceGroups/{resourceGroupName}/providers/Microsoft.ContainerRegistry/registries/{registryName}",
                **self.url_parameters
            )

        @property
        def method(self):
            return "GET"

        @property
        def error_format(self):
            return "MgmtErrorFormat"

        @property
        def url_parameters(self):
            parameters = {
                **self.serialize_url_param(
                    "registryName", self.ctx.args.registry_name,
                    required=True,
                ),
                **self.serialize_url_param(
                    "resourceGroupName", self.ctx.args.resource_group,
                    required=True,
                ),
                **self.serialize_url_param(
                    "subscriptionId", self.ctx.subscription_id,
                    required=True,
                ),
            }
            return parameters

        @property
        def query_parameters(self):
            parameters = {
                **self.serialize_query_param(
                    "api-version", "2024-11-01-preview",
                    required=True,
                ),
            }
            return parameters

        @property
        def header_parameters(self):
            parameters = {
                **self.serialize_header_param(
                    "Accept", "application/json",
                ),
            }
            return parameters

        def on_200(self, session):
            data = self.deserialize_http_content(session)
            self.ctx.set_var(
                "instance",
                data,
                schema_builder=self._build_schema_on_200
            )

        _schema_on_200 = None

        @classmethod
        def _build_schema_on_200(cls):
            if cls._schema_on_200 is not None:
                return cls._schema_on_200

            cls._schema_on_200 = AAZObjectType()
            _RemoveHelper._build_schema_registry_read(cls._schema_on_200)

            return cls._schema_on_200

    class RegistriesUpdate(AAZHttpOperation):
        CLIENT_TYPE = "MgmtClient"

        def __call__(self, *args, **kwargs):
            request = self.make_request()
            session = self.client.send_request(request=request, stream=False, **kwargs)
            if session.http_response.status_code in [202]:
                return self.client.build_lro_polling(
                    self.ctx.args.no_wait,
                    session,
                    self.on_200_201,
                    self.on_error,
                    lro_options={"final-state-via": "azure-async-operation"},
                    path_format_arguments=self.url_parameters,
                )
            if session.http_response.status_code in [200, 201]:
                return self.client.build_lro_polling(
                    self.ctx.args.no_wait,
                    session,
                    self.on_200_201,
                    self.on_error,
                    lro_options={"final-state-via": "azure-async-operation"},
                    path_format_arguments=self.url_parameters,
                )

            return self.on_error(session.http_response)

        @property
        def url(self):
            return self.client.format_url(
                "/subscriptions/{subscriptionId}/resourceGroups/{resourceGroupName}/providers/Microsoft.ContainerRegistry/registries/{registryName}",
                **self.url_parameters
            )

        @property
        def method(self):
            return "PATCH"

        @property
        def error_format(self):
            return "MgmtErrorFormat"

        @property
        def url_parameters(self):
            parameters = {
                **self.serialize_url_param(
                    "registryName", self.ctx.args.registry_name,
                    required=True,
                ),
                **self.serialize_url_param(
                    "resourceGroupName", self.ctx.args.resource_group,
                    required=True,
                ),
                **self.serialize_url_param(
                    "subscriptionId", self.ctx.subscription_id,
                    required=True,
                ),
            }
            return parameters

        @property
        def query_parameters(self):
            parameters = {
                **self.serialize_query_param(
                    "api-version", "2024-11-01-preview",
                    required=True,
                ),
            }
            return parameters

        @property
        def header_parameters(self):
            parameters = {
                **self.serialize_header_param(
                    "Content-Type", "application/json",
                ),
                **self.serialize_header_param(
                    "Accept", "application/json",
                ),
            }
            return parameters

        @property
        def content(self):
            subresource = self.serialize_content(self.ctx.selectors.subresource.required())
            return {"identity": subresource, }

        def on_200_201(self, session):
            data = self.deserialize_http_content(session)
            self.ctx.set_var(
                "instance",
                data,
                schema_builder=self._build_schema_on_200_201
            )

        _schema_on_200_201 = None

        @classmethod
        def _build_schema_on_200_201(cls):
            if cls._schema_on_200_201 is not None:
                return cls._schema_on_200_201

            cls._schema_on_200_201 = AAZObjectType()
            _RemoveHelper._build_schema_registry_read(cls._schema_on_200_201)

            return cls._schema_on_200_201

    class InstanceUpdateByJson(AAZJsonInstanceUpdateOperation):

        def __call__(self, *args, **kwargs):
            self._update_instance(self.ctx.selectors.subresource.required())

        def _update_instance(self, instance):
            _instance_value, _builder = self.new_content_builder(
                self.ctx.args,
                value=instance,
                typ=AAZIdentityObjectType
            )
            _builder.set_prop("userAssigned", AAZListType, ".mi_user_assigned", typ_kwargs={"flags": {"action": "remove"}})
            _builder.set_prop("systemAssigned", AAZStrType, ".mi_system_assigned", typ_kwargs={"flags": {"action": "remove"}})

            user_assigned = _builder.get(".userAssigned")
            if user_assigned is not None:
                user_assigned.set_elements(AAZStrType, ".")

            return _instance_value


class _RemoveHelper:
    """Helper class for Remove"""

    _schema_registry_read = None

    @classmethod
    def _build_schema_registry_read(cls, _schema):
        if cls._schema_registry_read is not None:
            _schema.id = cls._schema_registry_read.id
            _schema.identity = cls._schema_registry_read.identity
            _schema.location = cls._schema_registry_read.location
            _schema.name = cls._schema_registry_read.name
            _schema.properties = cls._schema_registry_read.properties
            _schema.sku = cls._schema_registry_read.sku
            _schema.system_data = cls._schema_registry_read.system_data
            _schema.tags = cls._schema_registry_read.tags
            _schema.type = cls._schema_registry_read.type
            return

        cls._schema_registry_read = _schema_registry_read = AAZObjectType()

        registry_read = _schema_registry_read
        registry_read.id = AAZStrType(
            flags={"read_only": True},
        )
        registry_read.identity = AAZIdentityObjectType()
        registry_read.location = AAZStrType(
            flags={"required": True},
        )
        registry_read.name = AAZStrType(
            flags={"read_only": True},
        )
        registry_read.properties = AAZObjectType(
            flags={"client_flatten": True},
        )
        registry_read.sku = AAZObjectType(
            flags={"required": True},
        )
        registry_read.system_data = AAZObjectType(
            serialized_name="systemData",
            flags={"read_only": True},
        )
        cls._build_schema_system_data_read(registry_read.system_data)
        registry_read.tags = AAZDictType()
        registry_read.type = AAZStrType(
            flags={"read_only": True},
        )

        identity = _schema_registry_read.identity
        identity.principal_id = AAZStrType(
            serialized_name="principalId",
            flags={"read_only": True},
        )
        identity.tenant_id = AAZStrType(
            serialized_name="tenantId",
            flags={"read_only": True},
        )
        identity.type = AAZStrType()
        identity.user_assigned_identities = AAZDictType(
            serialized_name="userAssignedIdentities",
        )

        user_assigned_identities = _schema_registry_read.identity.user_assigned_identities
        user_assigned_identities.Element = AAZObjectType()

        _element = _schema_registry_read.identity.user_assigned_identities.Element
        _element.client_id = AAZStrType(
            serialized_name="clientId",
            flags={"read_only": True},
        )
        _element.principal_id = AAZStrType(
            serialized_name="principalId",
            flags={"read_only": True},
        )

        properties = _schema_registry_read.properties
        properties.admin_user_enabled = AAZBoolType(
            serialized_name="adminUserEnabled",
        )
        properties.anonymous_pull_enabled = AAZBoolType(
            serialized_name="anonymousPullEnabled",
        )
        properties.auto_generated_domain_name_label_scope = AAZStrType(
            serialized_name="autoGeneratedDomainNameLabelScope",
        )
        properties.creation_date = AAZStrType(
            serialized_name="creationDate",
            flags={"read_only": True},
        )
        properties.data_endpoint_enabled = AAZBoolType(
            serialized_name="dataEndpointEnabled",
        )
        properties.data_endpoint_host_names = AAZListType(
            serialized_name="dataEndpointHostNames",
            flags={"read_only": True},
        )
        properties.encryption = AAZObjectType()
        properties.login_server = AAZStrType(
            serialized_name="loginServer",
            flags={"read_only": True},
        )
        properties.metadata_search = AAZStrType(
            serialized_name="metadataSearch",
        )
        properties.network_rule_bypass_options = AAZStrType(
            serialized_name="networkRuleBypassOptions",
        )
        properties.network_rule_set = AAZObjectType(
            serialized_name="networkRuleSet",
        )
        properties.policies = AAZObjectType()
        properties.private_endpoint_connections = AAZListType(
            serialized_name="privateEndpointConnections",
            flags={"read_only": True},
        )
        properties.provisioning_state = AAZStrType(
            serialized_name="provisioningState",
            flags={"read_only": True},
        )
        properties.public_network_access = AAZStrType(
            serialized_name="publicNetworkAccess",
        )
        properties.status = AAZObjectType(
            flags={"read_only": True},
        )
        properties.zone_redundancy = AAZStrType(
            serialized_name="zoneRedundancy",
        )

        data_endpoint_host_names = _schema_registry_read.properties.data_endpoint_host_names
        data_endpoint_host_names.Element = AAZStrType()

        encryption = _schema_registry_read.properties.encryption
        encryption.key_vault_properties = AAZObjectType(
            serialized_name="keyVaultProperties",
        )
        encryption.status = AAZStrType()

        key_vault_properties = _schema_registry_read.properties.encryption.key_vault_properties
        key_vault_properties.identity = AAZStrType()
        key_vault_properties.key_identifier = AAZStrType(
            serialized_name="keyIdentifier",
        )
        key_vault_properties.key_rotation_enabled = AAZBoolType(
            serialized_name="keyRotationEnabled",
            flags={"read_only": True},
        )
        key_vault_properties.last_key_rotation_timestamp = AAZStrType(
            serialized_name="lastKeyRotationTimestamp",
            flags={"read_only": True},
        )
        key_vault_properties.versioned_key_identifier = AAZStrType(
            serialized_name="versionedKeyIdentifier",
            flags={"read_only": True},
        )

        network_rule_set = _schema_registry_read.properties.network_rule_set
        network_rule_set.default_action = AAZStrType(
            serialized_name="defaultAction",
            flags={"required": True},
        )
        network_rule_set.ip_rules = AAZListType(
            serialized_name="ipRules",
        )

        ip_rules = _schema_registry_read.properties.network_rule_set.ip_rules
        ip_rules.Element = AAZObjectType()

        _element = _schema_registry_read.properties.network_rule_set.ip_rules.Element
        _element.action = AAZStrType()
        _element.value = AAZStrType(
            flags={"required": True},
        )

        policies = _schema_registry_read.properties.policies
        policies.azure_ad_authentication_as_arm_policy = AAZObjectType(
            serialized_name="azureADAuthenticationAsArmPolicy",
        )
        policies.export_policy = AAZObjectType(
            serialized_name="exportPolicy",
        )
        policies.quarantine_policy = AAZObjectType(
            serialized_name="quarantinePolicy",
        )
        policies.retention_policy = AAZObjectType(
            serialized_name="retentionPolicy",
        )
        policies.soft_delete_policy = AAZObjectType(
            serialized_name="softDeletePolicy",
        )
        policies.trust_policy = AAZObjectType(
            serialized_name="trustPolicy",
        )

        azure_ad_authentication_as_arm_policy = _schema_registry_read.properties.policies.azure_ad_authentication_as_arm_policy
        azure_ad_authentication_as_arm_policy.status = AAZStrType()

        export_policy = _schema_registry_read.properties.policies.export_policy
        export_policy.status = AAZStrType()

        quarantine_policy = _schema_registry_read.properties.policies.quarantine_policy
        quarantine_policy.status = AAZStrType()

        retention_policy = _schema_registry_read.properties.policies.retention_policy
        retention_policy.days = AAZIntType()
        retention_policy.last_updated_time = AAZStrType(
            serialized_name="lastUpdatedTime",
            flags={"read_only": True},
        )
        retention_policy.status = AAZStrType()

        soft_delete_policy = _schema_registry_read.properties.policies.soft_delete_policy
        soft_delete_policy.last_updated_time = AAZStrType(
            serialized_name="lastUpdatedTime",
            flags={"read_only": True},
        )
        soft_delete_policy.retention_days = AAZIntType(
            serialized_name="retentionDays",
        )
        soft_delete_policy.status = AAZStrType()

        trust_policy = _schema_registry_read.properties.policies.trust_policy
        trust_policy.status = AAZStrType()
        trust_policy.type = AAZStrType()

        private_endpoint_connections = _schema_registry_read.properties.private_endpoint_connections
        private_endpoint_connections.Element = AAZObjectType()

        _element = _schema_registry_read.properties.private_endpoint_connections.Element
        _element.id = AAZStrType(
            flags={"read_only": True},
        )
        _element.name = AAZStrType(
            flags={"read_only": True},
        )
        _element.properties = AAZObjectType(
            flags={"client_flatten": True},
        )
        _element.system_data = AAZObjectType(
            serialized_name="systemData",
            flags={"read_only": True},
        )
        cls._build_schema_system_data_read(_element.system_data)
        _element.type = AAZStrType(
            flags={"read_only": True},
        )

        properties = _schema_registry_read.properties.private_endpoint_connections.Element.properties
        properties.private_endpoint = AAZObjectType(
            serialized_name="privateEndpoint",
        )
        properties.private_link_service_connection_state = AAZObjectType(
            serialized_name="privateLinkServiceConnectionState",
        )
        properties.provisioning_state = AAZStrType(
            serialized_name="provisioningState",
            flags={"read_only": True},
        )

        private_endpoint = _schema_registry_read.properties.private_endpoint_connections.Element.properties.private_endpoint
        private_endpoint.id = AAZStrType()

        private_link_service_connection_state = _schema_registry_read.properties.private_endpoint_connections.Element.properties.private_link_service_connection_state
        private_link_service_connection_state.actions_required = AAZStrType(
            serialized_name="actionsRequired",
        )
        private_link_service_connection_state.description = AAZStrType()
        private_link_service_connection_state.status = AAZStrType()

        status = _schema_registry_read.properties.status
        status.display_status = AAZStrType(
            serialized_name="displayStatus",
            flags={"read_only": True},
        )
        status.message = AAZStrType(
            flags={"read_only": True},
        )
        status.timestamp = AAZStrType(
            flags={"read_only": True},
        )

        sku = _schema_registry_read.sku
        sku.name = AAZStrType(
            flags={"required": True},
        )
        sku.tier = AAZStrType(
            flags={"read_only": True},
        )

        tags = _schema_registry_read.tags
        tags.Element = AAZStrType()

        _schema.id = cls._schema_registry_read.id
        _schema.identity = cls._schema_registry_read.identity
        _schema.location = cls._schema_registry_read.location
        _schema.name = cls._schema_registry_read.name
        _schema.properties = cls._schema_registry_read.properties
        _schema.sku = cls._schema_registry_read.sku
        _schema.system_data = cls._schema_registry_read.system_data
        _schema.tags = cls._schema_registry_read.tags
        _schema.type = cls._schema_registry_read.type

    _schema_system_data_read = None

    @classmethod
    def _build_schema_system_data_read(cls, _schema):
        if cls._schema_system_data_read is not None:
            _schema.created_at = cls._schema_system_data_read.created_at
            _schema.created_by = cls._schema_system_data_read.created_by
            _schema.created_by_type = cls._schema_system_data_read.created_by_type
            _schema.last_modified_at = cls._schema_system_data_read.last_modified_at
            _schema.last_modified_by = cls._schema_system_data_read.last_modified_by
            _schema.last_modified_by_type = cls._schema_system_data_read.last_modified_by_type
            return

        cls._schema_system_data_read = _schema_system_data_read = AAZObjectType(
            flags={"read_only": True}
        )

        system_data_read = _schema_system_data_read
        system_data_read.created_at = AAZStrType(
            serialized_name="createdAt",
        )
        system_data_read.created_by = AAZStrType(
            serialized_name="createdBy",
        )
        system_data_read.created_by_type = AAZStrType(
            serialized_name="createdByType",
        )
        system_data_read.last_modified_at = AAZStrType(
            serialized_name="lastModifiedAt",
        )
        system_data_read.last_modified_by = AAZStrType(
            serialized_name="lastModifiedBy",
        )
        system_data_read.last_modified_by_type = AAZStrType(
            serialized_name="lastModifiedByType",
        )

        _schema.created_at = cls._schema_system_data_read.created_at
        _schema.created_by = cls._schema_system_data_read.created_by
        _schema.created_by_type = cls._schema_system_data_read.created_by_type
        _schema.last_modified_at = cls._schema_system_data_read.last_modified_at
        _schema.last_modified_by = cls._schema_system_data_read.last_modified_by
        _schema.last_modified_by_type = cls._schema_system_data_read.last_modified_by_type


__all__ = ["Remove"]
